// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Verifica se o serviço está ativo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/config": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Faz login na API Move/Intelbras, persiste credenciais (criptografadas se ` + "`" + `ENCRYPTION_KEY` + "`" + ` existir). ` + "`" + `webhookUrl` + "`" + ` é opcional. Resposta inclui ` + "`" + `token` + "`" + ` (JWT) e ` + "`" + `expiresIn` + "`" + ` (segundos, ver ` + "`" + `WS_TOKEN_TTL_SECONDS` + "`" + `). Use o JWT no header ` + "`" + `Authorization: Bearer` + "`" + ` em ` + "`" + `POST /v1/stations` + "`" + ` e ` + "`" + `DELETE /v1/config` + "`" + `. O JWT não substitui ` + "`" + `X-API-Key` + "`" + ` nas rotas que exigem esse header.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuração"
                ],
                "summary": "Configura credenciais (e token JWT)",
                "parameters": [
                    {
                        "description": "email e password (obrigatórios); webhookUrl e apiKey (opcionais)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token, expiresIn",
                        "schema": {
                            "$ref": "#/definitions/api.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "token unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "configuration failed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Apaga o usuário identificado pelo JWT retornado em ` + "`" + `POST /v1/config` + "`" + ` (header ` + "`" + `Authorization: Bearer` + "`" + `) e todos os dados relacionados (credenciais, webhooks, eventos) via cascade.",
                "tags": [
                    "Configuração"
                ],
                "summary": "Remove configuração e dados do usuário",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u0026lt;JWT\u0026gt;",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/config/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Indica se há configuração e se o token de acesso está presente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuração"
                ],
                "summary": "Status da configuração",
                "responses": {
                    "200": {
                        "description": "configured, tokenPresent, tokenExpiresAt, apiUsername",
                        "schema": {
                            "$ref": "#/definitions/api.ConfigStatusResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "configuration unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stations": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Valida o JWT (header ` + "`" + `Authorization: Bearer` + "`" + `) retornado por ` + "`" + `POST /v1/config` + "`" + ` e confere ` + "`" + `apiKey` + "`" + ` do JSON com a salva no configure. O corpo da resposta segue o mesmo esquema do payload periódico de webhook de estações.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estação"
                ],
                "summary": "Lista estações (Authorization: Bearer + apiKey no corpo)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u0026lt;JWT\u0026gt;",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "apiKey (igual ao /v1/config; use string vazia ou omita se não houver apiKey na config)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.StationsPostRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "userId, timestamp, stations",
                        "schema": {
                            "$ref": "#/definitions/api.StationsPushResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "stations unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ConfigRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "webhookUrl": {
                    "type": "string"
                }
            }
        },
        "api.ConfigResponse": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "type": "integer",
                    "example": 300
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "api.ConfigStatusResponse": {
            "type": "object",
            "properties": {
                "apiUsername": {
                    "type": "string",
                    "example": "usuario@empresa.com"
                },
                "configured": {
                    "type": "boolean",
                    "example": true
                },
                "tokenExpiresAt": {
                    "type": "string",
                    "example": "2026-03-25T10:30:00Z"
                },
                "tokenPresent": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unauthorized"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.StationsPostRequest": {
            "type": "object",
            "properties": {
                "apiKey": {
                    "type": "string",
                    "example": "sua-api-key-intelbras"
                }
            }
        },
        "api.StationsPushConnector": {
            "type": "object",
            "properties": {
                "connectorId": {
                    "type": "integer"
                },
                "connectorPk": {
                    "type": "integer"
                },
                "connectorType": {
                    "type": "string"
                },
                "erroInfo": {
                    "type": "string"
                },
                "errorCode": {
                    "type": "string"
                },
                "powerMax": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.StationsPushResponse": {
            "type": "object",
            "properties": {
                "stations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StationsPushStation"
                    }
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-05-04T12:00:00Z"
                },
                "userId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "api.StationsPushStation": {
            "type": "object",
            "properties": {
                "chargeBoxId": {
                    "type": "string"
                },
                "chargePointModel": {
                    "type": "string"
                },
                "chargePointVendor": {
                    "type": "string"
                },
                "connectors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.StationsPushConnector"
                    }
                },
                "description": {
                    "type": "string"
                },
                "fwVersion": {
                    "type": "string"
                },
                "ocppProtocol": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "defense.intelbras-cve-pro.com.br",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "EV Charging Status API",
	Description:      "API para configuração e consulta de estações de recarga (Move/Intelbras), `POST /v1/stations` com JWT, webhook opcional no worker. Rotas em tempo real fora desta especificação permanecem disponíveis no serviço.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
