// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Verifica se o serviço está ativo.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/v1/config": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Faz login na API Move/Intelbras, persiste credenciais (criptografadas se ` + "`" + `ENCRYPTION_KEY` + "`" + ` existir). ` + "`" + `webhookUrl` + "`" + ` é opcional. Resposta inclui ` + "`" + `token` + "`" + ` e ` + "`" + `expiresIn` + "`" + ` (segundos) para ` + "`" + `GET /v1/ws?token=` + "`" + ` ou cliente WebSocket.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuração"
                ],
                "summary": "Configura credenciais (e token WebSocket)",
                "parameters": [
                    {
                        "description": "email e password (obrigatórios); webhookUrl e apiKey (opcionais)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token, expiresIn",
                        "schema": {
                            "$ref": "#/definitions/api.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "invalid request",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "ws token unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "configuration failed",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Apaga o usuário indicado e todos os dados relacionados (credenciais, webhooks, eventos) via cascade.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Configuração"
                ],
                "summary": "Remove configuração e dados do usuário",
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/config/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Indica se há configuração e se o token de acesso está presente.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Configuração"
                ],
                "summary": "Status da configuração",
                "responses": {
                    "200": {
                        "description": "configured, tokenPresent, tokenExpiresAt, apiUsername",
                        "schema": {
                            "$ref": "#/definitions/api.ConfigStatusResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "configuration unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/stations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna a lista de estações de recarga (e conectores) da API Move/Intelbras, usando o token salvo ou renovando-o.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Estação"
                ],
                "summary": "Lista estações",
                "responses": {
                    "200": {
                        "description": "stations: array de estações",
                        "schema": {
                            "$ref": "#/definitions/api.StationsResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "stations unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/ws": {
            "get": {
                "description": "Upgrade HTTP para WebSocket. Envie o JWT em ` + "`" + `?token=` + "`" + ` ou no header ` + "`" + `Authorization: Bearer` + "`" + `. Mensagens são JSON (` + "`" + `userId` + "`" + `, ` + "`" + `stations` + "`" + `, ` + "`" + `timestamp` + "`" + `) no intervalo configurado em ` + "`" + `WS_PUBLISH_INTERVAL_SECONDS` + "`" + `.",
                "tags": [
                    "WebSocket"
                ],
                "summary": "Conexão WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT retornado por POST /v1/config ou GET /v1/ws/token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "401": {
                        "description": "missing ou invalid ws token",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/ws/stats": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Conexões ativas, mensagens enviadas, drops por backpressure e erros de escrita.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Métricas do hub WebSocket",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.WSHubStats"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/ws/token": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retorna ` + "`" + `token` + "`" + ` e ` + "`" + `expiresIn` + "`" + ` (segundos) para usar em ` + "`" + `GET /v1/ws?token=` + "`" + ` ou ` + "`" + `ws://.../v1/ws?token=` + "`" + `.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "WebSocket"
                ],
                "summary": "Token WebSocket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email do usuário (username em ` + "`" + `users` + "`" + `, igual ao POST /v1/config)",
                        "name": "username",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token, expiresIn",
                        "schema": {
                            "$ref": "#/definitions/api.ConfigResponse"
                        }
                    },
                    "400": {
                        "description": "username is required",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "unauthorized",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "user not found / sem credenciais",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "ws token unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ConfigRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "apiKey": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "webhookUrl": {
                    "type": "string"
                }
            }
        },
        "api.ConfigResponse": {
            "type": "object",
            "properties": {
                "expiresIn": {
                    "type": "integer",
                    "example": 300
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "api.ConfigStatusResponse": {
            "type": "object",
            "properties": {
                "apiUsername": {
                    "type": "string",
                    "example": "usuario@empresa.com"
                },
                "configured": {
                    "type": "boolean",
                    "example": true
                },
                "tokenExpiresAt": {
                    "type": "string",
                    "example": "2026-03-25T10:30:00Z"
                },
                "tokenPresent": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "unauthorized"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.StationsResponse": {
            "type": "object",
            "properties": {
                "stations": {
                    "description": "Estrutura varia conforme payload da API Move/Intelbras.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        },
        "api.WSHubStats": {
            "type": "object",
            "properties": {
                "activeUsers": {
                    "type": "integer"
                },
                "droppedByBackpressure": {
                    "type": "integer"
                },
                "messagesSent": {
                    "type": "integer"
                },
                "totalConnections": {
                    "type": "integer"
                },
                "writeErrors": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "integraodefense-apistatuscve-loefbt-f377b9-54-159-164-244.traefik.me",
	BasePath:         "/",
	Schemes:          []string{"https"},
	Title:            "EV Charging Status API",
	Description:      "API para configuração e consulta de estações de recarga (Move/Intelbras), envio opcional por webhook e push periódico por WebSocket (por usuário, via JWT).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
